version: '3'
services:
  strapi:
    image: strapi/strapi
    restart: always
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mysql
  phpmyadmin:
      image: phpmyadmin
      restart: always
      environment:
        PMA_ARBITRARY: 1
        PMA_HOST: mysql
        PMA_PORT: 3306
        PMA_USER: strapi
        PMA_PASSWORD: strapi
      ports:
        - 1338:80

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi